Small fix for unhandled connection issue
atd-schubert/node-tor-control pull request #4
Opened 2018-03-09 09:44 UTC by viocost

2018-03-11 18:31 UTC, atd-schubert requested changes
Please test if the callback function is not `undefined` first...

2018-03-11 18:31 UTC, atd-schubert commented on index.js
> +            cb(new Error("Error connecting to control port: " + err));
The callback is optional. Maybe you check if `cb` is `undefined` at the beginning and add a no-operation function to it, or you test (like used in the other parts) if `cb` exists before calling it.

```js
if (cb) {
  cb(new Error("Error connecting to control port: " + err));
}
```

2018-03-11 18:56 UTC, viocost commented
Fixed it

2018-03-12 16:01 UTC, atd-schubert approved these changes
Thanks!

2018-03-12 16:02 UTC, merged

2018-03-12 16:03 UTC, atd-schubert commented
I try to publish a new version on npm in the next hours

2018-03-12 17:38 UTC, viocost commented
Thank you! That's a great library!